// Do not edit this file, create local.config.js
module.exports = {
    // Your local web server project url.
    // examples:
    // http://localhost/[PROJECT]/public
    // http://[PROJECT].dev
    // NOTE: This setting does not affect production builds
    projectURL: 'http://[PROJECT].dev',
    // The path to the project assets relative to the projectURL
    // examples:
    // '/[PROJECT]/'
    // '/'
    // (always end with a trailing slash '/')
    publicPath: '/'
};