#!/bin/bash

if [ $# -lt 2 ]
  then
    echo "No enough arguments"
    echo "usage ./deploy HOSTNAME /folder PORT USER:GROUP"
    exit 1
fi

if [ "$3" == "" ]; then
    SSH_PORT="22"
else
    SSH_PORT="$3"
fi

if [ "$4" == "" ]; then
    WEB_USER="www-data:www-data"
else
    WEB_USER="$4"
fi

HOST="$1"
SCRIPT_PATH="$(dirname $0)"
REMOTE_PATH="$2"
FOLDERS="
public/storage
storage
storage/framework
storage/framework/views
storage/framework/cache
storage/framework/sessions
storage/logs
storage/app
"

if ! ssh -tt -o StrictHostKeyChecking=no -p $SSH_PORT $HOST 'test -e "'$REMOTE_PATH'"'; then
    echo -e "\nDIRECTORY $REMOTE_PATH NOT EXISTS\n"
    exit 1
fi

rsync -azP -e "ssh -p $SSH_PORT" --exclude-from "$SCRIPT_PATH/.exclude" --delete ./ "$HOST:$REMOTE_PATH"

ssh -tt -o StrictHostKeyChecking=no -p $SSH_PORT $HOST '
    cd "'$REMOTE_PATH'"

    for folder in '$FOLDERS'; do
        if [ ! -d "$folder" ]; then
            install -d "$folder"
            chmod +w "$folder"
        fi
    done

    php artisan migrate

    chown -R '$WEB_USER' .

    exit
'